### PR TITLE
添加工具栏功能若干，支持TeX渲染和实验性的mermaid支持

### PR DESCRIPTION
**Pull request by HerbertHe**
* 添加工具栏工具若干
* 添加TeX渲染支持
* 添加实验性的mermaid支持
* 添加响应式布局

### CODE REVIEW

**Comment by lishenyu16** [comment]
why the author still doesn't accept your PR

**Comment by HerbertHe** [comment]
> why the author still doesn't accept your PR

I don't know, the author has not updated this repo for several months

**Comment by lishenyu16** [comment]
> > why the author still doesn't accept your PR
> 
> I don't know, the author has not updated this repo for several months

can you please publish your own branch to npm? Your branch is far better than this one. Even some popular packages like express, is built-in  for many other packages.

**Comment by HerbertHe** [comment]
To be honest, I don't really want to publish my branch to npm due to respecting author, and I have not gotten any permission. If you really want to use my branch, you can use it by following my branch's using document in my repository. If Chinese document is not ok, I can try to write an English version. My branch still have some troubles can't solve, I have communicated with people in mermaid and issued about mermaidAPI bugs. Most of features were finished, and I overwritten some basic code by reading marked source code. If you want more features, you can issue in my branch. I do not often refresh my branch, you can get the more stable version in my branch's releases. I will keep going and contributting for open source. Thanks for your supporting!

**Comment by HerbertHe** [comment]
I am preparing for my branch to publish to npm, the new branch will keep in sync with my branch. [HerbertHe/for-editor-herb](https://github.com/HerbertHe/for-editor-herb)

**Comment by HerbertHe** [comment]
Now, you can use `yarn add for-editor-herb` to use this

**Pull request closed without merging**
